Repository atapas/covid-19, pull requests merged in 2020-05, with the labels that each got.

#16 issue-7-Ability for the users to select the Home Country and Persist it in LocalStorage
  assets/styles/sass/styles.scss
  src/js/Countries.js
  src/js/Country.js
  src/js/CountrySelector.js
  src/js/Home.js
  src/js/HomePageSelctor.js
  src/js/IndiaState.js
  src/js/IndiaStateCharts.js
  src/js/World.js
  src/js/covid-all/CompareWidget.js
  src/js/covid-all/CountryCasesWidget.js
  src/js/covid-all/OverAllWidget.js
  src/js/covid-all/StateIndiaMostConfirmed.js
  src/js/covid-all/StateIndiaMostRecovered.js
  src/js/covid-all/TopNDeathWidget.js
  src/js/covid-all/TopNRecoveredWidget.js
  src/js/covid-all/TopNTodayDeath.js
  src/js/time-series/FetchTimeSeries.js
  src/js/time-series/TimeSeries.js
  src/js/time-series/TimeSeriesBroken.js
  src/js/useFetch.js
Labels: enhancement, good first issue

#20 Persisting selected value on cancel.
  src/js/HomePageSelctor.js
Labels: bug

#21 Added a clear selection
  assets/styles/sass/styles.scss
  src/js/CountrySelector.js
Labels: enhancement

#23 bugfix/District-Level-Trends-on-demand-for-an-individual-District
  src/js/IndiaDistrict.js
Labels: bug
